### ISSUE TITLE
你曾经成功的用shadowsocks-elixir翻过墙吗？

### ISSUE THREAD

**Issue by luckypoem** [Sen/shadowsocks-elixir#1]
hi。
可否写份详细的安装教程？

**Comment by luckypoem** [comment]
hi.
root@ary:~/shadowsocks-elixir# ./shadowsocks_elixir
*\* (UndefinedFunctionError) undefined function: :local.main/1
    :local.main([])
    /private/tmp/elixir-C9hi/elixir-0.11.2/lib/elixir/lib/kernel/cli.ex:39: Kernel.CLI.run/2
    escript.erl:757: :escript.run/2
    escript.erl:277: :escript.start/1
    :init.start_em/1
    :init.do_boot/3

root@ary:~/shadowsocks-elixir#

怎么解决这个错误？

**Comment by Sen** [comment]
@luckypoem 这个东西我已经弃坑了，麻烦找别的项目。这个只是当时在0.12左右的版本尝试写一个ss而已。
